### ISSUE TITLE
Missing steps in Publish and subscribe 

### ISSUE THREAD

**Issue by IanHibbert** [meteor/simple-todos-vue#1]
In section 10.5 - after adding the "showPrivateButton", there is a step missing to pass in the prop value for "showPrivateButton" in the App.vue file. I found the code in the App.vue file on github but it's missing the written portion on the website.

**Comment by BrianMulhall** [comment]
ill look into this tonight, thanks for the feedback

**Comment by BrianMulhall** [comment]
https://github.com/meteor/tutorials/pull/199/files once this pull request goes live we should be all set with this ticket

**Comment by BrianMulhall** [comment]
this update has been published to the meteor site
